FROM oven/bun:1.3.10

WORKDIR  /app
COPY . .

ARG PUBLIC_SERVER_ADDRESS
ARG PUBLIC_SERVER_PORT
ENV PUBLIC_SERVER_ADDRESS=${PUBLIC_SERVER_ADDRESS}
ENV PUBLIC_SERVER_PORT=${PUBLIC_SERVER_PORT}

RUN bun install
RUN bun run build

CMD ["bun", "run", "prod"]
